### ISSUE TITLE
Integrate TS compiler to parse types to grammar

### ISSUE THREAD

**Issue by jazelly** [withcatai/node-llama-cpp#210]
### Feature Description

The GBNF works as a charm. Considering the consumer end are mostly typed, wouldn't it be better to support the conversion from type to grammar?

### The Solution

A simple solution is just to use TS compiler api to parse the AST to grammar.

### Considered Alternatives

Or can simply use [gbnfgen](https://github.com/intrinsiclabsai/gbnfgen/)

### Additional Context

I am raising this while I was playing with [this](https://grammar.intrinsiclabs.ai/)

### Related Features to This Feature Request

- [ ] Metal support
- [ ] CUDA support
- [X] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by giladgd** [comment]
I've considered this in the past and decided not to support it, since converting TS types to grammar requires either:
* placing a separate TS file and reading its content directly in your code - reading a `.ts` file like that is problematic for use in apps and libraries since the shipped code is transpiled to JS, and this is a source `.ts` file, so you'd have to mess with workarounds to make sure it exists and loads in the final code
* Writing the code inline as a string - loses its purpose as there are no type validations there, and it's not type-safe

Also, loading the source of a `.ts` file without using it in your TypeScript code by importing it like any other code won't use the types inside of it to ensure your code is valid, so you lose all the type safety that TypeScript offers.

The [JSON schema grammar provided by `node-llama-cpp`](https://withcatai.github.io/node-llama-cpp/guide/grammar#using-a-json-schema-grammar) is type-safe and makes use of TypeScript properly to provide type validations against the output that a model generates.

I think gbnfgen is cool, and thus [I've mentioned it in the documentation](https://withcatai.github.io/node-llama-cpp/guide/grammar#grammar-generation-libraries), but I haven't found it practical enough for TypeScript projects to actually integrate something like that directly into `node-llama-cpp`.

I have used the TypeScript compiler API in the past to read and modify codebases, so I'm well aware of its capabilities and how to use it to do things like that, so my main reason not to add built-in support for something like that in `node-llama-cpp` is due to it adding complexity to people's projects and not making good use of TypeScript's type safety system.

Anyway, thanks for the suggestion :)
