### ISSUE TITLE
Feature request: Langchain support

### ISSUE THREAD

**Issue by chethankumar** [withcatai/node-llama-cpp#23]
Is there a plan for langchain support

**Comment by giladgd** [comment]
There are no such plans at the moment, but you're welcome to open a PR for this

**Comment by nigel-daniels** [comment]
HI, I currently have a PR open on langchain that uses the node-llama-cpp bindings to let people use Llama2 with llama.cpp. You can take a look at the PR here: https://github.com/hwchase17/langchainjs/pull/2413 If any one has any advice on making this better I'd appreciate any thoughts :)

**Comment by giladgd** [comment]
Awesome :)
Thanks @nigel-daniels!

**Comment by nigel-daniels** [comment]
Let me know if it would be possible to connect at some point to learn more about the 2.0.0 changes? Id like to ensure the module I added us naking the best use of these bindings to encourage use all round.

**Comment by giladgd** [comment]
@nigel-daniels The bump to major version 2 was because I updated the library to adapt to breaking changes in `llama.cpp`.
Some of those breaking changes were the transition to GGUF models, so starting with version 2, only GGUF models are supported.
I hope there won't be any other user-facing breaking changes in `llama.cpp` again, but if there will be any then I'll probably have to bump the major version again.

BTW, all the version bumps of the package are done by [`semantic-release`](https://www.npmjs.com/package/semantic-release), so the merged PRs automatically affect the version of new package releases, and when a PR is marked as containing breaking changes it automatically bumps the package's major version.

**Comment by giladgd** [comment]
@nigel-daniels I think it should be safe to set something like this in the `package.json` of `langchain`:
```
"node-llama-cpp": "^2"
```

If there'll be any breaking changes in the API of `node-llama-cpp` then its major version will be bumped again, so any `2.x.x` should still be compatible with the current integration you added to `langchain`.
