### ISSUE TITLE
Unable to create a context

### ISSUE THREAD

**Issue by vlamanna** [withcatai/node-llama-cpp#283]
### Issue description

Create a context fail on Linux / AMD64 with CUDA

### Expected Behavior

The following code returns a context:

`const context = await model.createContext();`

### Actual Behavior

The following works fine on my Mac M1 environment but fails every time on linux/amd64 with CUDA. It returns the following error: Context is disposed.

I've tried adding:
`console.log(this._ctx.getContextSize()`
right after this line:
https://github.com/withcatai/node-llama-cpp/blob/beta/src/evaluator/LlamaContext/LlamaContext.ts#L82

And even there, I get the same error.

It works fine on 3.0.0-beta.32.

### Steps to reproduce

On linux/amd64 with CUDA, run the following:
`const context = await model.createContext();`

### My Environment

| Dependency               | Version             |
| ---                      | ---                 |
| Operating System         | Linux                    |
| CPU                      | Intel Xeon  |
| Node.js version          | 20.11.0             |
| Typescript version       | 5.5.3             |
| `node-llama-cpp` version | 3.0.0-beta.40             |

### Relevant Features Used

- [ ] Metal support
- [X] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by bqhuyy** [comment]
@vlamanna Have you tried to set `contextSize`? This error may be `out of memory` since `contextSize` is too large.

**Comment by vlamanna** [comment]
I have tried different models like:
- Meta-Llama-3.1-8B
- Phi-3.1-mini-4k
- all-MiniLM-L12-v2
- all-MiniLM-L6-v2
- bge-small-en-v1.5
- snowflake-arctic-embed-s

I have also tried to set the contextSize to 512.

It works fine on my Macbook Pro M1 but fails on a AWS G4dn.xlarge instance with 1 GPU and 16 GB of VRAM. Version beta.32 works fine on both.

**Comment by vlamanna** [comment]
`this._ctx = new this._llama._bindings.AddonContext(this._model._model, removeNullFields({
    seed: seed != null ? Math.max(-1, Math.floor(seed)) : undefined,
    contextSize: this._contextSize * this._totalSequences, // each sequence needs its own <contextSize> of cells
    batchSize: this._batchSize,
    sequences: this._totalSequences,
    flashAttention: this._flashAttention,
    threads: Math.max(0, Math.floor(threads)),
    embeddings: _embeddings,
    noSeed: _noSeed
}));
console.log('Context', this._ctx.getContextSize());`

At this point, the constructor didn't throw an error and `this._ctx` exists. But calling getContextSize() throws "Context is disposed".

**Comment by giladgd** [comment]
@vlamanna I think I have an idea of why this happens, and this has to do with garbage collection happening before a persistent reference is being created in the native side, which is prevalent on CUDA because the loading of the model takes more time, in which the garbage collection is more likely to run.
I'm currently investigating it and will hopefully release a new version with the fix soon.

**Comment by vlamanna** [comment]
@giladgd Let me know if you need some help.

**Comment by giladgd** [comment]
@vlamanna I found the cause for this issue and opened a PR for this (#285).
The issue actually was using uninitialized variable, so the existing memory for it sometimes complied with `true` and sometimes complied with `false`.
It appears that macOS does some kind of cleaning to the memory before letting a binary use it (perhaps to avoid leaking data from one process to another), but this is not the case on Linux, hence the reason it didn't reproduce on macOS.

This issue was introduced as part of a refactor I've done to organize the native code better, and the problematic line was the last line in this snippet:
https://github.com/withcatai/node-llama-cpp/blob/826334b33a793f0485bd869de805a897199fae28/llama/addon/AddonContext.cpp#L400-L409

It should have been written without `bool` to reference the class variable instead of defining a new variable for the current context.

**Comment by vlamanna** [comment]
@giladgd Makes sense, thank you. I will test in our environment.
