### ISSUE TITLE
refactor: extract the advance features to an independent high-level library package

### ISSUE THREAD

**Issue by snowyu** [withcatai/node-llama-cpp#354]
### Scenario

I have already implemented the chat apply the proper system Prompt template automatically base on llama-server.
https://github.com/offline-ai/cli

I wish to use the basic features like in llama-server.

### Benefit

* Focus on core functionality;
* Better isolation of JS and NAPI libraries;
* Easier for more developers to develop or join the development;

### The Solution

Only keep the core features in the main library.

Just little simple APIs to call the LLM like llama-server:

* chatCompletion
* infill
* embedding
* tokenize/detokenize
* loraAdapters

The lowlevel api usages:

```ts
const llama = await getLlama();
const model = await llama.loadModel({
    modelPath: path.join(__dirname, "models", "Meta-Llama-3-8B-Instruct.Q4_K_M.gguf"),
    useMlock: ...,
})
// can changed in any time.
model.parameters.threads = 4;
model.parameters.rope.scaling = LlamaRopeScaling.yarn

model.loraAdapters.load("path/to/lora")
model.loraAdapters.remove("path/to/lora")
model.loraAdapters.clear()

export const AIGenerationFinishReasons = [
  'stop',
  'length',
  'content_filter',
  'tool_calls',
  'function_call',
  'abort', // triggered by abort signal
  'error',
  'other', null,
] as const // extract from OpenAI
export type AIGenerationFinishReason = typeof AIGenerationFinishReasons[number]
interface AIResult {
  content?: string|Uint8Array|...;
  finishReason?: AIGenerationFinishReason;
  options?: any;  // the applied LLM options
  stop?: boolean; // for stream mode
}
const response: AIResult|ReadableStream<AIResult> = model.chatCompletion(prompt: string|tokens[], {stream: true, max_tokens: 1024, temperature: 0.2, signal: ...})
```

### Considered Alternatives

Cut out a standalone version with only core functionality.

### Related Features to This Feature Request

- [ ] Metal support
- [ ] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by giladgd** [comment]
`node-llama-cpp` attempts to include everything you need to run LLMs without the need to integrate other packages.
I’ve put in a lot of work to ensure the developer is experience of using `node-llama-cpp` is great and as simple as it can be, but I still plan to simplify it even further.
Extracting functionality to other libraries that need to be used to benefit from `node-llama-cpp` will not contribute to a better developer experience and thus I don’t plan to do it.

Regarding extracting internal functionality to other libraries that will be used by `node-llama-cpp`, it depends on the particular use case, but in general I prefer keeping everything contained in `node-llama-cpp` to make it much easier to maintain.
Some features are impossible to implement and maintain without deep integration into `llama.cpp` via internal underlying API that I don’t want to expose directly for other libraries to be able to build upon due to:
* The underlying API being changed constantly, so I cannot ensure its stability or even existence for other libraries to build upon. This internal use of such APIs for the use cases that depend on it was constantly updated and maintained for it to continue to work.
* Improper use of such underlying API can cause the entire process to crash. I don’t want that to even be possible. The maintenance burden of this is too great, especially for the niche use case that it would allow.
   For the use cases that do need such internal access, I prefer people to contribute code to `node-llama-cpp` to facilitate what they want to achieve instead - this way it can be maintained in a stable manner.

`node-llama-cpp` is not intended to just be a binding to the `llama.cpp` API. All the APIs that are exposed were chosen to be exposed to facilitate common uses cases that people seek for, thus those uses cases are implemented alongside the actual bindings and the C++ side of those implementations.

If there’s something that you like to achieve with `node-llama-cpp` that isn’t possible with the existing API, you’re encouraged to open an issue or a PR to add high-level features that facilitate what you want to achieve.

**Comment by giladgd** [comment]
The API of `node-llama-cpp` is intended to be high-level, which is why it doesn’t allow changing parameters of loaded models and contexts, and instead you have to recreate them.
Changing such parameters of loaded models/contexts is a niche use case that makes it more complicated for all other uses cases.
In high-level functional code you don’t expect objects to change, and instead be recreated - this facilitates more stable and readable code, and is especially important in TypeScript projects.
There are some optimizations I’ve put in place to ensure this is also performant and efficient in the native side, but I plan to add even more in the future.

**Comment by snowyu** [comment]
> Extracting functionality to other libraries that need to be used to benefit from node-llama-cpp will not contribute to a better developer experience and thus I don’t plan to do it.

I do not understand it. The divide and conquer strategy benefits everyone. It also keeps the project simple and stupid (KISS).

When all functional blocks can be independent (library) rather than tightly coupled with each other, maintenance and improvement will naturally become easier (you don't need to know extra information). For example, I have extracted the system prompt template based on rule matching as a separate [prompt](https://github.com/isdk/ai-tool-prompt.js) library, and implemented the following features:

* Management of various prompts
* Collection The LLM System template prompts With Enhancement (guessing corresponding system templates based on the model file name)
* Multiple versions support under the same system prompt template file
* Recommendation of parameters for LLM models
* Extensible multiple template formats to write system prompt template: jinjia2 (hf), golang (ollama), python fstring (langchain). Here jinjia2 is used as the default template format.
* Extensible file format: `yaml`, `json`. Here yaml format is used as the default file format.

Its core API is very simple to use, just one function: [findPrompt](https://github.com/isdk/ai-tool-prompt.js/blob/b42ea19a1120d035076cd96a10cd6acfc76999ae/src/prompt.ts#L145)

> Changing such parameters of loaded models/contexts is a niche use case that makes it more complicated for all other uses cases.

For example,`nctx`(Context Window size) is related to memory and quality. When the prompt is a short text, we want to set nctx smaller to improve the answer quality and reduce memory usage; when it is a long text, we have to set nctx larger.

I have no idea. Why not sperate the data in the memory and process them to keep them simple enough.
