### ISSUE TITLE
Electron sample app crash on Mac with speciffic model Meta-Llama-3.1-8B-Instruct.Q4_K_M.gguf

### ISSUE THREAD

**Issue by sytolk** [withcatai/node-llama-cpp#361]
### Issue description

Electron sample app crash on Mac

### Expected Behavior

no crash

### Actual Behavior

crash

### Steps to reproduce

Im testing with template https://github.com/withcatai/node-llama-cpp/tree/master/templates/electron-typescript-react and installed app .dmg file (the result is the same). After browse and choose model `Meta-Llama-3.1-8B-Instruct.Q4_K_M.gguf` Electron app crash with [the log](https://pastebin.com/pKcRtHHB)

### My Environment

OS: macOS 23.4.0 (x64)
Node: 18.18.2 (x64)
node-llama-cpp: 3.1.1

Metal: not supported by llama.cpp on Intel Macs

CPU model: Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
Math cores: 6
Used RAM: 99.24% (31.76GB/32GB)
Free RAM: 0.75% (248.02MB/32GB)

### Relevant Features Used

- [ ] Metal support
- [ ] CUDA support
- [ ] Vulkan support
- [ ] Grammar
- [ ] Function calling

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start.

**Comment by sytolk** [comment]
It appears that crash depend of the model I dont have problem with `gemma-2-2b-it-Q4_K_M.gguf` file

**Comment by giladgd** [comment]
There seems to be an issue with one of the latest `llama.cpp` releases that introduced this crash on macOS when Metal is not used (I managed to reproduce it on an M1 machine by building with Metal support disabled).
It only happens on Electron, and probably has something to do with Electron's strict guards on memory allocation.

From my tests, it seems that the `llama.cpp` release that's bundled with `node-llama-cpp` version [`3.1.0`](https://github.com/withcatai/node-llama-cpp/releases/tag/v3.1.0) is not affected, so I recommend locking your `package.json` to that version until this issue is fixed.

I'll continue investigating the root cause of this.

---

To make it easier to reproduce this issue on Apple Silicone Macs, these command can be used:
```bash
mkdir repro
cd repro
npm init -y
npm install node-llama-cpp@3.1.1 electron
npx --no node-llama-cpp source build --gpu false
npx electron ./node_modules/node-llama-cpp/dist/cli/cli.js chat --prompt 'Hi there!' --gpu false
```
